03 mongodb
Yarzik7/nodejs-homework-rest-api pull request #3
Opened 2023-08-14 19:28 UTC by Yarzik7

2023-08-15 05:06 UTC, KhYulian commented on controllers/contacts.js
> +  res.status(201).json(await Contact.create(req.body));
Власне, сервіси можна далі використовувати просто замість роботи з fs робити запити в db

2023-08-15 05:06 UTC, KhYulian commented on controllers/contacts.js
>    }
```suggestion
```

2023-08-15 05:07 UTC, KhYulian commented on controllers/contacts.js
>    }
для валідації використовуйте виключно joi. Такі перевірки непотрібні

2023-08-15 05:07 UTC, KhYulian commented on models/contacts.js
> +};
```suggestion
``` 
це зайве

2023-08-15 05:07 UTC, KhYulian commented on models/contacts.js
> +});
винесіть в окремий файл e.g. /utils/validation/contactValidationSchemas.js

2023-08-15 05:08 UTC, KhYulian requested changes
Потрібні правки

2023-08-15 05:09 UTC, KhYulian commented on routes/api/contacts.js
>  const ctrl = require('../../controllers/contacts');
зробіть деструктуризацію

2023-08-15 23:26 UTC, Yarzik7 commented on controllers/contacts.js
> +  res.status(201).json(await Contact.create(req.body));
Виправив

2023-08-15 23:26 UTC, Yarzik7 commented on controllers/contacts.js
>    }
Виправив

2023-08-15 23:26 UTC, Yarzik7 commented on models/contacts.js
> +};
Виправив

2023-08-15 23:26 UTC, Yarzik7 commented on models/contacts.js
> +});
Виправив

2023-08-15 23:26 UTC, Yarzik7 commented on routes/api/contacts.js
>  const ctrl = require('../../controllers/contacts');
Виправив

2023-08-16 06:36 UTC, KhYulian approved these changes
Чудова робота

2023-08-16 06:36 UTC, merged